//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTE_V1._8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SGTE2Entities : DbContext
    {
        public SGTE2Entities()
            : base("name=SGTE2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Aluno> Tbl_Aluno { get; set; }
        public virtual DbSet<Tbl_Cliente> Tbl_Cliente { get; set; }
        public virtual DbSet<Tbl_Endereco> Tbl_Endereco { get; set; }
        public virtual DbSet<Tbl_Escola> Tbl_Escola { get; set; }
        public virtual DbSet<Tbl_Funcionario> Tbl_Funcionario { get; set; }
        public virtual DbSet<Tbl_Hora_Viagem> Tbl_Hora_Viagem { get; set; }
        public virtual DbSet<Tbl_Login> Tbl_Login { get; set; }
        public virtual DbSet<Tbl_Motorista> Tbl_Motorista { get; set; }
        public virtual DbSet<Tbl_Passageiro_Viagem> Tbl_Passageiro_Viagem { get; set; }
        public virtual DbSet<Tbl_Veiculo> Tbl_Veiculo { get; set; }
        public virtual DbSet<Tbl_Viagem> Tbl_Viagem { get; set; }
    
        public virtual ObjectResult<string> stp_CadastroFuncionario(Nullable<int> iD, string funcao, Nullable<int> matricula, string nome, string endereco, string bairro, string cidade, string cEP, string estado, string tel_Residencial, string tel_Celular, string email, string rG, string cPF, Nullable<System.DateTime> data_Nasc, string sexo, Nullable<int> nivelAcesso, Nullable<int> nivel, string mensagem)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var funcaoParameter = funcao != null ?
                new ObjectParameter("Funcao", funcao) :
                new ObjectParameter("Funcao", typeof(string));
    
            var matriculaParameter = matricula.HasValue ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var enderecoParameter = endereco != null ?
                new ObjectParameter("Endereco", endereco) :
                new ObjectParameter("Endereco", typeof(string));
    
            var bairroParameter = bairro != null ?
                new ObjectParameter("Bairro", bairro) :
                new ObjectParameter("Bairro", typeof(string));
    
            var cidadeParameter = cidade != null ?
                new ObjectParameter("Cidade", cidade) :
                new ObjectParameter("Cidade", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var tel_ResidencialParameter = tel_Residencial != null ?
                new ObjectParameter("Tel_Residencial", tel_Residencial) :
                new ObjectParameter("Tel_Residencial", typeof(string));
    
            var tel_CelularParameter = tel_Celular != null ?
                new ObjectParameter("Tel_Celular", tel_Celular) :
                new ObjectParameter("Tel_Celular", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var rGParameter = rG != null ?
                new ObjectParameter("RG", rG) :
                new ObjectParameter("RG", typeof(string));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            var data_NascParameter = data_Nasc.HasValue ?
                new ObjectParameter("Data_Nasc", data_Nasc) :
                new ObjectParameter("Data_Nasc", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var nivelAcessoParameter = nivelAcesso.HasValue ?
                new ObjectParameter("NivelAcesso", nivelAcesso) :
                new ObjectParameter("NivelAcesso", typeof(int));
    
            var nivelParameter = nivel.HasValue ?
                new ObjectParameter("Nivel", nivel) :
                new ObjectParameter("Nivel", typeof(int));
    
            var mensagemParameter = mensagem != null ?
                new ObjectParameter("Mensagem", mensagem) :
                new ObjectParameter("Mensagem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("stp_CadastroFuncionario", iDParameter, funcaoParameter, matriculaParameter, nomeParameter, enderecoParameter, bairroParameter, cidadeParameter, cEPParameter, estadoParameter, tel_ResidencialParameter, tel_CelularParameter, emailParameter, rGParameter, cPFParameter, data_NascParameter, sexoParameter, nivelAcessoParameter, nivelParameter, mensagemParameter);
        }
    }
}
